version: "3"
services:
  collabolancer-client:
    build: ./collabolancer-client/builded
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure
    depends_on:
      - lisk-explorer
      - lisk-faucet
    networks:
      - lisk-collabolancer
    environment:
      - REACT_APP_NODE=${COLLABOLANCER_NODE_URL}
      - REACT_APP_EXTENDED_API=${COLLABOLANCER_EXTENDED_API_URL}
      - REACT_APP_EXPLORER_URL=${COLLABOLANCER_EXPLORER_URL}
      - REACT_APP_FAUCET_URL=${COLLABOLANCER_FAUCET_URL}
      - REACT_APP_NETWORK_HASH=${COLLABOLANCER_NETHASH}
      - REACT_APP_NETWORK_NAME=${COLLABOLANCER_NETWORK_NAME}
    volumes:
      - ./collabolancer-client/letsencrypt:/etc/letsencrypt
      - ./collabolancer-client/nginx/conf.d:/etc/nginx/conf.d

  lisk-explorer:
    image: lisk/explorer:2.3.0-rc.1
    depends_on:
      - collabolancer-cache
    ports:
      - "6040:6040"
    networks:
      - lisk-collabolancer
    restart: on-failure
    volumes:
      - ./lisk-explorer/config.global.js:/home/lisk/lisk-explorer/config.global.js
      - ./lisk-explorer/config.js:/home/lisk/lisk-explorer/config.js
    environment:
      - LISK_URL_HTTP=${COLLABOLANCER_NODE_URL}
      - LISK_URL_WS=${COLLABOLANCER_NODE_WS}
      - ENABLE_MARKET_FEATURES=false
      - REDIS_HOST=collabolancer-cache
      - FREEGEOIP_URL=https://geoip.lisk.io

  lisk-faucet:
    image: lisk/faucet:3.0.0-beta.0
    volumes:
      - ./lisk-faucet/api/lisk.js:/home/lisk/lisk-faucet/api/lisk.js
    depends_on:
      - collabolancer-cache
    expose:
      - 3200
    networks:
      - lisk-collabolancer
    restart: on-failure
    environment:
      - NODE_ENV=production
      - REDIS_HOST=collabolancer-cache
      - REDIS_PORT=6379
      - LISK_CORE_URL=${COLLABOLANCER_NODE_URL}
      - LISK_CORE_NETHASH=${COLLABOLANCER_NETHASH}
      - LISK_CORE_NETWORK_NAME=${COLLABOLANCER_NETWORK_NAME}
      - LISK_FAUCET_PASSPHRASE=${COLLABOLANCER_FAUCET_PASSPHRASE}
      - LISK_FAUCET_ADDRESS=${COLLABOLANCER_FAUCET_ADDRESS}
      - LISK_FAUCET_AMOUNT=${COLLABOLANCER_FAUCET_AMOUNT}
      - LISK_FAUCET_TTL=${COLLABOLANCER_FAUCET_TTL}
      - LISK_EXPLORER_URL=${COLLABOLANCER_EXPLORER_URL}
      - CAPTCHA_PUBLICKEY=${CAPTCHA_PUBLICKEY}
      - CAPTCHA_PRIVATEKEY=${CAPTCHA_PRIVATEKEY}

  collabolancer-cache:
    image: redis:alpine
    networks:
      - lisk-collabolancer
    restart: on-failure

  explorer-cache-candles:
    image: lisk/explorer:2.3.0-rc.1
    depends_on:
      - collabolancer-cache
    networks:
      - lisk-collabolancer
    environment:
      - REDIS_HOST=collabolancer-cache
    command: ./node_modules/grunt-cli/bin/grunt candles:build

networks:
  lisk-collabolancer:
